# Generated by Django 5.2 on 2025-05-09 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('housing', 'Housing'), ('transport', 'Transport'), ('food', 'Food'), ('healthcare', 'Healthcare'), ('personal', 'Personal'), ('entertainment', 'Entertainment'), ('debt', 'Debt'), ('savings', 'Savings'), ('miscellaneous', 'Miscellaneous'), ('custom', 'Custom')], max_length=100)),
                ('custom_category', models.CharField(blank=True, max_length=100)),
                ('recurring_monthly', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
