# Generated by Django 5.2 on 2025-05-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_general_savings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenses',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='General_Savings',
            new_name='General_Saving',
        ),
    ]
