# Generated by Django 5.2 on 2025-05-09 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_expenses_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('emergency fund', 'Emergency Fund'), ('travel / holiday', 'Travel / Holiday'), ('new home', 'New Home'), ('home renovation', 'Home Renovation'), ('car / vehicle', 'Car / Vehicle'), ('education / courses', 'Education / Courses'), ('wedding / event', 'Wedding / Event'), ('tech / gadgets', 'Tech / Gadgets'), ('christmas / gifts', 'Christmas / Gifts'), ('special event', 'Special Event'), ('gifts', 'Gifts'), ('rainy day fund', 'Rainy Day Fund'), ('investment fund', 'Investment Fund'), ('luxury purchase', 'Luxury Purchase'), ('other', 'Other')], max_length=100)),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline_ongoing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No I want to set a deadline')], max_length=3)),
                ('deadline', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
