# Generated by Django 5.2 on 2025-05-09 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_savings_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repayment_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('credit card', 'Credit Card'), ('loan', 'Loan'), ('student loan', 'Student Loan'), ('mortgage', 'Mortgage'), ('car finance', 'Car Finance'), ('buy now pay later', 'But Now Pay Later'), ('medical bills', 'Medical Bills'), ('overdraft', 'Overdraft'), ('utility arrears', 'Utility Arrears'), ('tax debt', 'Tax Debt'), ('family or friend loan', 'Family or Friend Loan'), ('business loan', 'Business Loan'), ('other', 'Other')], max_length=100)),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline_ongoing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No I want to set a deadline')], max_length=3)),
                ('deadline', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
