# Generated by Django 5.2 on 2025-05-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_repayment_goal'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment_goal',
            name='deadline_ongoing',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No I want to set a deadline')]),
        ),
        migrations.AlterField(
            model_name='savings_goal',
            name='deadline_ongoing',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No I want to set a deadline')]),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
