# Generated by Django 5.2.1 on 2025-05-15 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_customuser_username_alter_customuser_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
