# Generated by Django 5.2.1 on 2025-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savings_goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
