# Generated by Django 5.2.1 on 2025-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_budget_date_alter_savings_goal_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment_goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
