# Generated by Django 5.2.1 on 2025-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_repayment_goal_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment_goal',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='savings_goal',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
