# Generated by Django 5.2.1 on 2025-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_repayment_goal_current_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment_goal',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='savings_goal',
            name='current_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
